/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acenta;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Zahid
 */
public class rezervasyonEkran extends javax.swing.JFrame {

    
     String adres = "jdbc:mysql://94.73.170.236/acenta";
    String username = "fsm";
    String password = "RRrv34U8";
    
    int otel_id=123456;
    int oda_id;
    int oda_fiyat;
    String giris_tarih;
    String cikis_tarih;
    String sehir;
    int musteri_bonus;
    public rezervasyonEkran(int otel_id,int oda_fiyat,String giris_tarih,String cikis_tarih,String sehir) {
        this.otel_id=otel_id;
        this.oda_fiyat=oda_fiyat;
        this.giris_tarih=giris_tarih;
        this.cikis_tarih=cikis_tarih;
        this.sehir=sehir;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yenimusteri = new javax.swing.JButton();
        bonus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        odano = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        odemeyontem = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kartno = new javax.swing.JTextField();
        rezervasyonyap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bilgigetir = new javax.swing.JButton();
        tc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        yenimusteri.setText("yeni müşteri");
        yenimusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenimusteriActionPerformed(evt);
            }
        });

        bonus.setText("0");
        bonus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bonusPropertyChange(evt);
            }
        });

        jLabel5.setText("ad: -");

        jLabel13.setText("kullanılacak bonus");

        jLabel6.setText("soyad: -");

        jLabel1.setText("oda no");

        jLabel7.setText("oda no: -");

        odano.setEditable(false);

        jLabel8.setText("giriş tarih: -");

        odemeyontem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nakit", "kredikartı", "çek" }));
        odemeyontem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                odemeyontemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel9.setText("çıkış tarih: -");

        jLabel2.setText("ödeme yöntemi");

        jLabel10.setText("Şehir: -");

        jLabel3.setText("kart/hesap no:");

        jLabel11.setText("Fiyat: -");

        kartno.setEditable(false);

        rezervasyonyap.setText("rezervasyon yap");
        rezervasyonyap.setEnabled(false);
        rezervasyonyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezervasyonyapActionPerformed(evt);
            }
        });

        jLabel4.setText("müşteri tc");

        bilgigetir.setText("bilgileri getir");
        bilgigetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgigetirActionPerformed(evt);
            }
        });

        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        tc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcKeyPressed(evt);
            }
        });

        jLabel12.setText("Müşteri bonus: -");

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odemeyontem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odano, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bilgigetir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tc)
                            .addComponent(kartno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yenimusteri)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(41, 41, 41)
                        .addComponent(rezervasyonyap)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(odano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odemeyontem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kartno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenimusteri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bilgigetir)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rezervasyonyap)
                    .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bonusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bonusPropertyChange
        jLabel11.setText(""+(oda_fiyat-Integer.parseInt(bonus.getText())));
    }//GEN-LAST:event_bonusPropertyChange

    private void rezervasyonyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezervasyonyapActionPerformed
         try {
             rezervasyon r = new rezervasyon();
             r.rezervasyonYap(tc.getText(),odemeyontem.getSelectedIndex(),otel_id, Integer.parseInt(bonus.getText()));
             
             JOptionPane.showMessageDialog(this, "rezervasyon yapıldı");
             anaMenu a=new anaMenu();
             a.setVisible(true);
             this.dispose();
         } catch (SQLException ex) {
             Logger.getLogger(rezervasyonEkran.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_rezervasyonyapActionPerformed

    private void bilgigetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgigetirActionPerformed
        try {
            

            musteri mus = new musteri(); // getmusteri metodunu çağırmak için
            musteri m = new musteri(); //get ile alınan müşteriyi aktarmak için
            m = mus.getmusteribytc(tc.getText());
            musteri_bonus = mus.bonus;
            jLabel5.setText("ad: " + m.ad);
            jLabel6.setText("soyad: " + m.soyad);
            jLabel7.setText("oda no: " + oda_id);
            jLabel8.setText("giriş tarih: " + giris_tarih);
            jLabel9.setText("çıkış tarih: " + cikis_tarih);
            jLabel10.setText("Şehir: " + sehir);
            jLabel11.setText("fiyat: " + oda_fiyat);
            jLabel12.setText("fiyat: " + musteri_bonus);
            
            if(m.ad!=null) rezervasyonyap.setEnabled(true);
            
            

        } catch (SQLException ex) {
            Logger.getLogger(odemeEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bilgigetirActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed

    }//GEN-LAST:event_tcActionPerformed

    private void tcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcKeyPressed

    }//GEN-LAST:event_tcKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try {
             System.out.println(otel_id);
             rezervasyon r =new rezervasyon();
             oda_id=r.oteldekiSiradakiBosOdaId(otel_id);
             System.out.println(otel_id);
             odano.setText(oda_id+"");
             
         } catch (SQLException ex) {
             Logger.getLogger(rezervasyonEkran.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_formWindowOpened

    private void odemeyontemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_odemeyontemPopupMenuWillBecomeInvisible
         if (odemeyontem.getSelectedIndex() > 0) {
            kartno.setText("");
            kartno.setEditable(true);
        } else {
            kartno.setText("");
            kartno.setEditable(false);
        }
    }//GEN-LAST:event_odemeyontemPopupMenuWillBecomeInvisible

    private void yenimusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenimusteriActionPerformed
        musteriEkleEkran mE=new musteriEkleEkran();
        mE.setVisible(true);
    }//GEN-LAST:event_yenimusteriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        otelSorgu os=new otelSorgu();
        os.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rezervasyonEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rezervasyonEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rezervasyonEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rezervasyonEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              // new rezervasyonEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgigetir;
    private javax.swing.JTextField bonus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kartno;
    private javax.swing.JTextField odano;
    private javax.swing.JComboBox odemeyontem;
    private javax.swing.JButton rezervasyonyap;
    private javax.swing.JTextField tc;
    private javax.swing.JButton yenimusteri;
    // End of variables declaration//GEN-END:variables
}
