/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acenta;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zahid
 */
public class tablolar extends javax.swing.JFrame {

    String adres = "jdbc:mysql://94.73.170.236/acenta";
    String username = "fsm";
    String password = "RRrv34U8";

    /**
     * Creates new form tablolar
     */
    public tablolar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Seçili kaydı sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tablodaki bütün verileri sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<--");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
         ///   jtable ı yeni dataları çekerek yenile
        try {
            int satirsayisi = 0;
            int columnCount = 0;
            Acenta a = new Acenta();
            
            satirsayisi = (a.tablodakiVeriSayisi(jComboBox1.getSelectedItem() + ""));

            Connection con = null;

            con = DriverManager.getConnection(adres, username, password);
            Statement stat = con.createStatement();

            ResultSet res = stat.executeQuery("select * from acenta." + jComboBox1.getSelectedItem());
            ResultSetMetaData metadata = res.getMetaData();
            columnCount = metadata.getColumnCount();

            Object columnNames[] = new Object[columnCount];
            for (int i = 0; i < columnCount; i++) {
                columnNames[i] = metadata.getColumnName(i+1);
            }
            Object rowData[][] = new Object[satirsayisi][columnNames.length];        
            
           
                for (int i = 0;res.next(); i++) {
                    for (int j = 0; j < columnNames.length; j++) {
                        rowData[i][j]=res.getString(j+1);
                    }
                }
                
            
            
            
            DefaultTableModel model = new DefaultTableModel(rowData, columnNames);
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(tablolar.class.getName()).log(Level.SEVERE, null, ex);
        }
         ///   jtable ı yeni dataları çekerek yenile
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
          //comboboxa databseden tabloları çekerek koy
            Connection con = null;

            con = DriverManager.getConnection(adres, username, password);
            ResultSet resultSet = con.getMetaData().getCatalogs();
            String[] types = {"TABLE"};
            resultSet = con.getMetaData()
                    .getTables("acenta", null, "%", types);
            String tableName = "";
            while (resultSet.next()) {
                tableName = resultSet.getString(3);
                jComboBox1.addItem(tableName);
                // System.out.println("Table Name = " + tableName);
            }
            resultSet.close();

        } catch (SQLException ex) {
            Logger.getLogger(tablolar.class.getName()).log(Level.SEVERE, null, ex);
        }
         //comboboxa databseden tabloları çekerek koy
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            //seçili satırı databaseden sil
            Connection con = DriverManager.getConnection(adres, username, password);
            PreparedStatement preparedStmt = con.prepareStatement("delete from "+jComboBox1.getSelectedItem()+" where "+jTable1.getColumnName(0)+" = ?");
            preparedStmt.setString(1, (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            
            preparedStmt.executeUpdate();
            //seçili satırı databaseden sil
            
            
            
            
            
            ///   jtable ı yeni dataları çekerek yenile
            int satirsayisi = 0;
            int columnCount = 0;
            Acenta a = new Acenta();
            
            satirsayisi = (a.tablodakiVeriSayisi(jComboBox1.getSelectedItem() + ""));

            con = DriverManager.getConnection(adres, username, password);
            Statement stat = con.createStatement();

            ResultSet res = stat.executeQuery("select * from acenta." + jComboBox1.getSelectedItem());
            ResultSetMetaData metadata = res.getMetaData();
            columnCount = metadata.getColumnCount();

            Object columnNames[] = new Object[columnCount];
            for (int i = 0; i < columnCount; i++) {
                columnNames[i] = metadata.getColumnName(i+1);
            }
            Object rowData[][] = new Object[satirsayisi][columnNames.length];        //{ { "Row1-Column1", "Row1-Column2", "Row1-Column3" },{ "Row2-Column1", "Row2-Column2", "Row2-Column3" } };
            
           
                for (int i = 0;res.next(); i++) {
                    for (int j = 0; j < columnNames.length; j++) {
                        rowData[i][j]=res.getString(j+1);
                    }
                }
                
            
            
            
            DefaultTableModel model = new DefaultTableModel(rowData, columnNames);
            jTable1.setModel(model);
            ///   jtable ı yeni dataları çekerek yenile
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(tablolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
        
        try {
            Connection con = DriverManager.getConnection(adres, username, password);
            PreparedStatement preparedStmt = con.prepareStatement("delete from "+jComboBox1.getSelectedItem());
            preparedStmt.executeUpdate();
            
            
            
            ///   jtable ı yeni dataları çekerek yenile
            int satirsayisi = 0;
            int columnCount = 0;
            Acenta a = new Acenta();
            
            satirsayisi = (a.tablodakiVeriSayisi(jComboBox1.getSelectedItem() + ""));

            con = DriverManager.getConnection(adres, username, password);
            Statement stat = con.createStatement();

            ResultSet res = stat.executeQuery("select * from acenta." + jComboBox1.getSelectedItem());
            ResultSetMetaData metadata = res.getMetaData();
            columnCount = metadata.getColumnCount();

            Object columnNames[] = new Object[columnCount];
            for (int i = 0; i < columnCount; i++) {
                columnNames[i] = metadata.getColumnName(i+1);
            }
            Object rowData[][] = new Object[satirsayisi][columnNames.length];        //{ { "Row1-Column1", "Row1-Column2", "Row1-Column3" },{ "Row2-Column1", "Row2-Column2", "Row2-Column3" } };
            
           
                for (int i = 0;res.next(); i++) {
                    for (int j = 0; j < columnNames.length; j++) {
                        rowData[i][j]=res.getString(j+1);
                    }
                }
                
            
            
            
            DefaultTableModel model = new DefaultTableModel(rowData, columnNames);
            jTable1.setModel(model);
            ///   jtable ı yeni dataları çekerek yenile
            
        } catch (SQLException ex) {
            Logger.getLogger(tablolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         anaMenu a=new anaMenu();
         a.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
